# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c59e4ffc1f1a8e8c896770234dc31e2783c87462202d9360397e7f23a5849af10d4b56e6adaf35ba173f026be1844f8e4741c6f00c1d422af4cfed744fdf7ea1

test:
  secret_key_base: 8f3f43a5fdc079b2df7b48ae44d5e24bc99145d5a985170fec9ea9d7bfa4d632298c73c9b93a7a7ad0bf04f20b09d11dda3f57979bf41ca6c2906ffc8de74c2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
